# Generated by Django 6.0.3 on 2026-04-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('bag', 'Bag'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('meter', 'Meter'), ('litre', 'Litre'), ('piece', 'Piece')], max_length=50),
        ),
    ]
