# Generated by Django 6.0.3 on 2026-04-07 06:10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_material_name_ci'),
        ),
    ]
