# Generated by Django 6.0.3 on 2026-04-13 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_materialusage_and_stock_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('size_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='materials.material')),
            ],
            options={
                'ordering': ['material__name', 'size_mm', 'label'],
            },
        ),
        migrations.AddField(
            model_name='materialstock',
            name='material_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='materials.materialvariant'),
        ),
        migrations.CreateModel(
            name='MaterialVariantPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='materials.materialvariant')),
            ],
            options={
                'ordering': ['-date', 'variant__material__name', 'variant__size_mm', 'variant__label'],
            },
        ),
        migrations.AddConstraint(
            model_name='materialvariant',
            constraint=models.UniqueConstraint(fields=('material', 'size_mm'), name='unique_material_variant_size'),
        ),
        migrations.AddConstraint(
            model_name='materialvariantprice',
            constraint=models.UniqueConstraint(fields=('variant', 'date'), name='unique_variant_price_per_day'),
        ),
    ]
