# Generated by Django 6.0.3 on 2026-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_materialvariant_materialstock_material_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('bag', 'Bag'), ('kg', 'Kilogram'), ('ton', 'Ton'), ('meter', 'Meter'), ('litre', 'Litre'), ('piece', 'Piece'), ('other', 'Other')], max_length=50),
        ),
    ]
