# Generated by Django 6.0.3 on 2026-04-13 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_clientreceipt_history'),
        ('labour', '0004_casuallabourentry'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreceipt',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='MiscellaneousExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paid_to_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('labour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labour.labour')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
