# Generated by Django 6.0.3 on 2026-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_clientreceipt_payment_mode_miscellaneousexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientreceipt',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientreceipt',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientreceipt',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
