# Generated by Django 6.0.3 on 2026-04-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_clientreceipt_cheque_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='phase_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
