# Generated by Django 6.0.3 on 2026-04-07 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendortransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid bank account number with 6 to 30 digits.', regex='^\\d{6,30}$')]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='document_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid IFSC code in the format BBBB0CCCCCC.', regex='^[A-Z]{4}0[A-Z0-9]{6}$')]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
