# Generated by Django 6.0.3 on 2026-04-07 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendor_bank_account_number_vendor_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Aadhar number with 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid PAN number in the format AAAAA9999A (e.g., ABCDE1234F).', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')]),
        ),
    ]
