# Generated by Django 6.0.3 on 2026-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorpayment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
