# Generated by Django 6.0.3 on 2026-04-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('per_day_wage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LabourAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labour.labour')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='LabourPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('paid_amount', models.FloatField(default=0)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labour.labour')),
            ],
        ),
    ]
