# Generated by Django 6.0.3 on 2026-04-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0002_labourpayment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='labour_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
