# Generated by Django 6.0.3 on 2026-04-13 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('labour', '0003_labour_labour_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasualLabourEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_name', models.CharField(max_length=255)),
                ('labour_type', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'Casual labour entry',
                'verbose_name_plural': 'Casual labour entries',
            },
        ),
    ]
